### ISSUE TITLE
name 'pyZZUF' is not defined

### ISSUE THREAD

**Issue by alyssahyq** [nezlooy/pyZZUF#2]
<img width="708" alt="Screen Shot 2020-08-18 at 1 09 23 PM" src="https://user-images.githubusercontent.com/59900390/90543718-17249f80-e154-11ea-8170-3d7d11728373.png">
I tried this as README.md in Jupyter Notebook (Python 3.6.9). Could you tell me what I am doing wrong?

**Comment by nezlooy** [comment]
Thank you for trying pyZZUF!
I've never tried to use pyZZUF in a Jupyter Notebook, as an example I was able to solve it this way:
![image](https://user-images.githubusercontent.com/427329/90545268-0e9e8a00-e191-11ea-9b87-1c63f9647ee1.png)

**Comment by alyssahyq** [comment]
> Thank you for trying pyZZUF!
> I've never tried to use pyZZUF in a Jupyter Notebook, as an example I was able to solve it this way:
> ![image](https://user-images.githubusercontent.com/427329/90545268-0e9e8a00-e191-11ea-9b87-1c63f9647ee1.png)

Thank you for your quick reply! It works now :-)
